# Generated by Django 4.0.1 on 2022-01-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('RW', 'REWATCH'), ('NT', 'NOTES'), ('PR', 'PRACTICE'), ('TB', 'TEXTBOOK'), ('FC', 'FLASHCARDS'), ('OT', 'OTHER')], default='OT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default=False, max_length=255)),
                ('exam', models.CharField(choices=[('M1', 'MIDTERM_1'), ('M2', 'MIDTERM_2'), ('M3', 'MIDTERM_3'), ('M4', 'MIDTERM_4'), ('FN', 'FINAL')], default='M1', max_length=2)),
                ('score', models.FloatField()),
                ('professor', models.CharField(max_length=255)),
                ('ta', models.CharField(max_length=255)),
                ('lec_attendance', models.BooleanField()),
                ('rec_attendance', models.BooleanField()),
                ('hrs_study', models.IntegerField()),
                ('major', models.CharField(max_length=255)),
                ('minor', models.CharField(max_length=255)),
                ('avg_sleep', models.IntegerField()),
                ('extracurricular_hours', models.IntegerField()),
                ('musician', models.BooleanField()),
                ('artist', models.BooleanField()),
                ('athlete', models.BooleanField()),
                ('lifestyle', models.CharField(choices=[('SE', 'SEDENTARY'), ('MO', 'MODERATE'), ('AC', 'ACTIVE')], default='MO', max_length=2)),
                ('num_semesters', models.IntegerField()),
                ('coop', models.BooleanField()),
                ('retake', models.BooleanField()),
                ('study_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.studymethod')),
            ],
        ),
    ]
