# Generated by Django 4.0.1 on 2022-01-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_courselisting_professor_teachingassistant_exam_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='artist',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='athlete',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lifestyle',
            field=models.CharField(choices=[('SE', 'SEDENTARY'), ('MO', 'MODERATE'), ('AC', 'ACTIVE')], default='MO', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='musician',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='num_semesters',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.professor'),
        ),
    ]
