# Generated by Django 4.0.1 on 2022-01-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_courselisting_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='letter_grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='A', max_length=2),
        ),
    ]
