# Generated by Django 4.0.1 on 2022-01-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_exam_letter_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='lec_attendance',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='rec_attendance',
            field=models.BooleanField(null=True),
        ),
    ]
