# Generated by Django 4.0.1 on 2022-01-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_exam_coop_alter_exam_retake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='hrs_study',
            field=models.IntegerField(null=True),
        ),
    ]
